---
# The name to use for the server
server_name: "voltha"
# Use virtualbox for development
vProvider: "virtualbox"
#vagrant_box: "ubuntu/xenial64"
# This determines if test mode is active
testMode: "false"
# This determines if installer mode is active
installMode: "false"
# Use KVM for production
#vProvider: "KVM"
