- name: JQ is present
  apt:
    name: jq
    force: yes
  tags: [common]

- name: Host is present
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ item.host_ip }}"
    line: "{{ item.host_ip }} {{ item.host_name }}"
  with_items:
    - host_ip: "10.100.198.220"
      host_name: "voltha"
  tags: [common]

- name: Latest apt packages
  apt:
    name: "{{ item }}"
  with_items:
    - debian-keyring
    - debian-archive-keyring
    - python-dev
    - libssl-dev
    - libffi-dev
    - libpcap-dev
    - python-virtualenv
    - jq
    - python-nose
    - python-flake8
    - python-scapy
  tags: [common]

- name: Services are not running
  service:
    name: "{{ item }}"
    state: stopped
  ignore_errors: yes
  with_items:
    - puppet
    - checf-client
  tags: [common]

- name: Ensure known_hosts file is absent
  file:
    path: "{{ ansible_env['HOME'] }}/.ssh/known_hosts"
    state: absent

- name: Disable Known Host Checking
  copy:
    src: files/ssh_config
    dest: "{{ ansible_env['HOME'] }}/.ssh/config"
    owner: "{{ ansible_env['SUDO_USER'] }}"
    group: "{{ ansible_env['SUDO_USER'] }}"
    mode: 0600
