hosts: [
  { host_ip: "10.100.198.220", host_name: "voltha"},
]

use_latest_for:
  - debian-keyring
  - debian-archive-keyring
  - python-dev
  - kafkacat
  - libssl-dev
  - libffi-dev
  - libpcap-dev
  - python-virtualenv
  - jq
  - python-nose
  - python-flake8
  - python-scapy
#  - python-libpcap

obsolete_services:
  - puppet
  - chef-client
