version: "3"
services:
  voltha:
    image: cord/voltha:latest
    deploy:
      replicas: 3
    entrypoint:
      - voltha/voltha/main.py
      - -v
      - --consul=consul:8500
      - --fluentd=fluentd:24224
      - --kafka=kafka
      - --rest-port=8880
      - --grpc-port=50555
      - --instance-id-is-container-name
      - --interface=eth2
      - --backend=consul
      - --inter-core-subnet=10.0.1.0/24
      - --pon-subnet=10.0.1.0/24

    networks:
      - net
    ports:
      - "8880:8880"
      - "18880:18880"
      - "50555:50555"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

networks:
  net:
     external:
       name: voltha_net

