version: "3"
services:

#
# Deploying a Fluentd cluster using this file assumes that overlay network 'voltha_net'
# has already been created. To deploy the fluentd cluster, issue the command:
#
#     docker stack deploy -c docker-compose-fluentd-cluster.yml fluentd
#
# This spins up two Fluentd Forwarders and one each Fluentd Aggregator-Active, Fluentd Aggregator-Standby.
# The forwards listens for voltha components logs on port 23224 and sends them towards Fluentd Aggregator. 
# Fluentd Aggregator writes them to their host mounted disk
#

  fluentdactv:
    image: fluent/fluentd
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - voltha-net
    ports:
      - "24224"
    volumes:
      - "/var/log/voltha:/fluentd/log"

  fluentdstby:
    image: fluent/fluentd
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - voltha-net
    ports:
      - "24224"
    volumes:
      - "/var/log/voltha:/fluentd/log"

networks:
  voltha-net:
    external:
      name: voltha_net

