#
# This stackfile deploys dashd to a docker swarm.
#
# Dashd depends on:
# - consul     (service)
# - kafka      (service)
# - grafana    (service)
# - voltha_net (overlay network)
#
# To deploy the stack, issue the command:
#
#     docker stack deploy -c docker-compose-stats-swarm.yml stats
#

version: "3"
services:
  dashd:
    image: cord/dashd
    deploy:
      replicas: 1
    entrypoint:
      - /dashd/dashd/main.py
      - --kafka=kafka
      - --consul=consul:8500
      - --grafana_url=http://admin:admin@grafana:80/api
      - --topic=voltha.kpis
      - --docker_host=${DOCKER_HOST_IP}
    networks:
      - voltha-net
      
networks:
  voltha-net:
    external:
      name: voltha_net

