#
# This Docker stackfile deploys a docker insecure registry
#
#
#     docker stack deploy -c docker-compose-registry.yml registry
#

version: "3"
services:
  registry:
    image: registry:2
    restart: always
    deploy:
      replicas: 1
    ports:
      - "5001:5000"
    volumes:
      - /cord/incubator/voltha/registry_data/registry_volume:/var/lib/registry
