- hosts: installer
  remote_user: vinstall
  serial: 1
  vars:
    target: installer
  roles:
    - common
    - docker
    - docker-compose
    - installer
    - docker-registry
- hosts: voltha
  remote_user: vagrant
  serial: 1
  vars:
    target: installer
  roles:
    - voltha
